name: Actualizar feed contratapa

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'  # todos los días a las 10:00 (Argentina, UTC-3)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar requests
        run: pip3 install requests

      - name: Ejecutar script
        run: python3 generate_feed.py

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Traer últimos cambios del repositorio remoto
  run: |
    git reset --hard HEAD
    git pull origin main --rebase

      - name: Subir cambios
        run: |
          git add feed.xml
          git commit -m "Actualizar contratapa" || echo "Sin cambios"
          git push origin main
